/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package waiter;

import waiter.Communicator.Communicator;
import waiter.EchoProtocol.EchoProtocol;
import waiter.Listener.Listener;
import waiter.Messenger.Messenger;

class App {

    public static void main(String[] args) {

        int port = 4424;
        Listener listener = new Listener();
        Messenger messenger = new Messenger(new EchoProtocol());
        EchoServer echoServer = new EchoServer(new Communicator(listener, messenger));
        echoServer.start(port);
    }
}
