/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package waiter;

import waiter.Reportable.Communicator;
import waiter.Protocol.EchoProtocol;
import waiter.Awaitable.Listener;
import waiter.Transportable.Messenger;

class App {

    public static void main(String[] args) {

        int port = 4424;
        Listener listener = new Listener();
        Messenger messenger = new Messenger(new EchoProtocol());
        EchoServer echoServer = new EchoServer(new Communicator(listener, messenger));
        echoServer.start(port);
    }
}
